BUILD_BROTLI=yes
BUILD_CAPNP=no
BUILD_CRC32C=yes
BUILD_HIREDIS=no
BUILD_LEVELDB=no
BUILD_LLVM=yes
BUILD_SNAPPY=yes
BUILD_SQLCIPHER=no
BUILD_SQLITE=no
BUILD_STAGE2=yes
BUILD_ZSTD=yes
BUILD_LZ4=yes
BUILD_PROPELLER=no

# Prefer zlib-ng.
BUILD_ZLIB_NG=yes
BUILD_ZLIB=no

# Prefer AWS LC.
BUILD_OPENSSL=no
BUILD_AWS_LC=yes

RELEASE=yes
HARDEN=yes
SECURE=OFF
GUARDED=OFF
CFI=no
MPK=no

LLVM_PROJECTS="clang;lld;lldb;bolt;polly"
LLVM_RUNTIMES="compiler-rt;libcxx;libcxxabi;libunwind"

USE_ZLIB=ng
USE_SQLITE=vanilla
USE_MUSL_CROSSMAKE=yes
USE_SCCACHE=no
USE_LTO=yes
USE_WIDE_VECTORS=no
CLEAN_BEFORE_BUILD=yes
MUSL_USE_MIMALLOC=yes
MUSL_USE_LTO=yes
MAKE_SYMLINK=yes

MODERN_X86_64_ARCH_TARGET=x86-64-v3
MODERN_X86_64_ARCH_TUNE=znver3
MODERN_AARCH64_ARCH_TARGET=armv8.2-a+crypto+crc
MODERN_AARCH64_ARCH_TUNE=generic

PREFER_COMPILER_FAMILY=clang

