# shellcheck shell=bash
# Target front-ends for a toolchain prefix (stage 1 or the bundle): clang config files,
# <triple>-clang symlinks, GCC-named musl shims, and CMake toolchain files. All paths are
# relative (<CFGDIR>, CMAKE_CURRENT_LIST_DIR) so the prefix can be relocated.

render_cfg() {
  local t="$1"
  case "$(triple_os "$t")" in
    linux)
      printf '%s\n' \
        "--target=$t" \
        "--sysroot=<CFGDIR>/../sysroot/$t" \
        "-rtlib=compiler-rt" \
        "-unwindlib=libunwind" \
        "-stdlib=libc++" \
        "-fuse-ld=lld"
      ;;
    darwin)
      printf '%s\n' \
        "--target=$(triple_cpu "$t")-apple-macos$MACOS_MIN" \
        "-isystem <CFGDIR>/../sysroot/$t/usr/include" \
        "-L<CFGDIR>/../sysroot/$t/usr/lib" \
        "-fuse-ld=lld"
      ;;
  esac
}

render_toolchain_cmake() {
  local t="$1"
  cat <<EOF
# Generated by elide-toolchain for $t.
# Usage: cmake -DCMAKE_TOOLCHAIN_FILE=<this file> ...
get_filename_component(_ET_ROOT "\${CMAKE_CURRENT_LIST_DIR}/../../.." ABSOLUTE)
set(CMAKE_C_COMPILER "\${_ET_ROOT}/bin/$t-clang")
set(CMAKE_CXX_COMPILER "\${_ET_ROOT}/bin/$t-clang++")
set(CMAKE_ASM_COMPILER "\${_ET_ROOT}/bin/$t-clang")
set(CMAKE_AR "\${_ET_ROOT}/bin/llvm-ar" CACHE FILEPATH "")
set(CMAKE_RANLIB "\${_ET_ROOT}/bin/llvm-ranlib" CACHE FILEPATH "")
set(CMAKE_NM "\${_ET_ROOT}/bin/llvm-nm" CACHE FILEPATH "")
set(CMAKE_STRIP "\${_ET_ROOT}/bin/llvm-strip" CACHE FILEPATH "")
EOF
  case "$(triple_os "$t")" in
    linux)
      cat <<EOF
set(CMAKE_SYSROOT "\${_ET_ROOT}/sysroot/$t")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
EOF
      ;;
    darwin)
      cat <<EOF
set(CMAKE_OSX_DEPLOYMENT_TARGET "$MACOS_MIN" CACHE STRING "")
set(CMAKE_OSX_ARCHITECTURES "$(triple_cpu "$t")" CACHE STRING "")
list(APPEND CMAKE_PREFIX_PATH "\${_ET_ROOT}/sysroot/$t/usr")
EOF
      ;;
  esac
}

install_musl_shims() {
  local prefix="$1" t="$2" p tool
  p="$(musl_gcc_prefix "$t")"
  install -m 0755 "$ROOT_DIR/src/shims/musl-gcc" "$prefix/bin/$p-gcc"
  for tool in g++ cc c++ ar ranlib nm strip; do
    ln -sfn "$p-gcc" "$prefix/bin/$p-$tool"
  done
}

install_frontends() {
  local prefix="$1" t
  mkdir -p "$prefix/bin" "$prefix/share/elide-toolchain/cmake"
  for t in $ALL_TARGETS; do
    render_cfg "$t" > "$prefix/bin/$t.cfg"
    ln -sfn clang "$prefix/bin/$t-clang"
    ln -sfn clang++ "$prefix/bin/$t-clang++"
    render_toolchain_cmake "$t" > "$prefix/share/elide-toolchain/cmake/$t.cmake"
    if [ "$(triple_libc "$t")" = musl ]; then install_musl_shims "$prefix" "$t"; fi
  done
}
