#!/usr/bin/env bash
# Move every submodule to its latest stable release tag (or branch tip), stage the new
# gitlinks, and regenerate the component pin block in versions.env.
# Usage: scripts/bump-submodules.sh   (submodules must be initialized)
set -euo pipefail
ROOT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd -P)"
cd "$ROOT_DIR"

# path|mode|selector
#   tag:     newest tag matching the ERE selector (prereleases excluded)
#   branch:  tip of the named branch
#   default: tip of the remote's default branch
SPEC='
aws-lc|tag|v[0-9]+\.[0-9]+\.[0-9]+
brotli|tag|v[0-9]+\.[0-9]+\.[0-9]+
capnp|tag|v1\.[0-9]+\.[0-9]+
cflags|branch|main
crc32c|tag|[0-9]+\.[0-9]+\.[0-9]+
glibc|branch|release/2.34/master
hiredis|tag|v[0-9]+\.[0-9]+\.[0-9]+
leveldb|tag|[0-9]+\.[0-9]+
llvm|tag|llvmorg-23\.[0-9]+\.[0-9]+
llvm-propeller|default|
lz4|tag|v[0-9]+\.[0-9]+\.[0-9]+
mimalloc|tag|v3\.[0-9]+\.[0-9]+
musl|branch|elide-v1.2.5
openssl|tag|openssl-[0-9]+\.[0-9]+\.[0-9]+
snappy|tag|[0-9]+\.[0-9]+\.[0-9]+
sqlcipher|tag|v[0-9]+\.[0-9]+\.[0-9]+
sqlite|default|
zlib|default|
zlib-ng|tag|[0-9]+\.[0-9]+\.[0-9]+
zstd|tag|v[0-9]+\.[0-9]+\.[0-9]+
'

var_of() { echo "$1" | tr 'a-z-' 'A-Z_'; }
strip_tag() { echo "$1" | sed -E 's/^(v|llvmorg-|openssl-)//'; }
url_of() { git -C "$1" remote get-url origin; }

block=""
while IFS='|' read -r path mode sel; do
  [ -n "$path" ] || continue
  [ -e "$path/.git" ] || { echo "submodule $path is not initialized" >&2; exit 1; }
  v="$(var_of "$path")"
  case "$mode" in
    tag)
      tag="$(git ls-remote --tags --refs "$(url_of "$path")" | awk '{sub("refs/tags/","",$2); print $2}' \
        | grep -E "^${sel}\$" | grep -viE 'rc|alpha|beta|pre|dev' | sort -V | tail -1)"
      [ -n "$tag" ] || { echo "no tag matching $sel for $path" >&2; exit 1; }
      git -C "$path" fetch -q --depth 1 origin "refs/tags/$tag:refs/tags/$tag"
      git -C "$path" checkout -q "refs/tags/$tag"
      line="${v}_VERSION=$(strip_tag "$tag")" ;;
    branch)
      git -C "$path" fetch -q --depth 1 origin "$sel"
      git -C "$path" checkout -q FETCH_HEAD
      line="${v}_REF=${sel}" ;;
    default)
      git -C "$path" fetch -q --depth 1 origin HEAD
      git -C "$path" checkout -q FETCH_HEAD
      line="${v}_REF=HEAD" ;;
    *) echo "bad mode $mode for $path" >&2; exit 1 ;;
  esac
  git add "$path"
  block+="${v}_REV=$(git -C "$path" rev-parse HEAD)"$'\n'"${line}"$'\n'
  echo "$path -> ${line#*=} ($(git -C "$path" rev-parse --short HEAD))"
done <<< "$SPEC"

python3 - "$ROOT_DIR/versions.env" "$block" <<'PYEOF'
import re, sys
path, block = sys.argv[1], sys.argv[2]
begin = "# >>> component pins (generated by scripts/bump-submodules.sh)"
end = "# <<< component pins"
text = open(path).read()
new = f"{begin}\n{block}{end}\n"
if begin in text:
    text = re.sub(re.escape(begin) + r".*?" + re.escape(end) + r"\n", lambda _: new, text, flags=re.S)
else:
    text = text.rstrip("\n") + "\n\n" + new
open(path, "w").write(text)
PYEOF
echo "versions.env updated"
